### ISSUE TITLE
Recompiling with qt5.15

### ISSUE THREAD

**Issue by fredboudon** [conda-forge/libqglviewer-feedstock#2]
### Comment:

@Tobias-Fischer: Would it be possible to recompile libqglviewer with qt 5.15?
With the actual qt 5.12, the sip files of the corresponding pyqt are distributed in $CONDA_PREFIX/share and I cannot rebuild the PyQGLViewer bindings.
Thanks a lot.

Fred

**Comment by Tobias-Fischer** [comment]
Fixed in #3
